/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class recognition_VehicleRecognition */

#ifndef _Included_recognition_VehicleRecognition
#define _Included_recognition_VehicleRecognition
#ifdef __cplusplus
extern "C" {
#endif
#undef recognition_VehicleRecognition_FORMAT_NV21
#define recognition_VehicleRecognition_FORMAT_NV21 0L
#undef recognition_VehicleRecognition_FORMAT_RGBA
#define recognition_VehicleRecognition_FORMAT_RGBA 1L
#undef recognition_VehicleRecognition_ERROR_CODE_FACE_NUM
#define recognition_VehicleRecognition_ERROR_CODE_FACE_NUM -2L
/*
 * Class:     recognition_VehicleRecognition
 * Method:    InitialInstance
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_recognition_VehicleRecognition_InitialInstance
  (JNIEnv *, jobject, jstring);

/*
 * Class:     recognition_VehicleRecognition
 * Method:    RecognizeRGBA
 * Signature: (J[III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_recognition_VehicleRecognition_RecognizeRGBA
  (JNIEnv *, jobject, jlong, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
